name: Test name
port: 9999
endpoints:
- path: /test
  method: GET
  action:
    mockResponse:
      statusCode:
        conditional:
          condition:
            random: {}
          ifTrue:
            static: 500
          ifFalse:
            success: {}
      headers:
        conditional:
          condition:
            random: {}
          ifTrue:
            static:
              header_1: first header
              header_2: second header
          ifFalse:
            empty: {}
      body:
        conditional:
          condition:
            random: {}
          ifTrue:
            static: "true"
          ifFalse:
            static: "false"
- path: /proxy
  action:
    proxy:
      toUrl:
        static: http://localhost:9999
- path: /conditionalAction/true
  method: GET
  action:
    mockResponse:
      statusCode:
        static: 500
      headers:
        empty: {}
      body:
        static: "true"
- path: /conditionalAction
  method: GET
  action:
    conditional:
      condition:
        random: {}
      ifTrue:
        proxy:
          toUrl:
            static: http://localhost:9999/conditionalAction/true
      ifFalse:
        mockResponse:
          statusCode:
            static: 200
          headers:
            static:
              header_1: header_1
          body:
            static: from ifFalse part