name: Test name
port: 9999
endpoints:
- path: /test
  method: GET
  action:
    mockResponse:
      statusCode:
        static: 500
      headers:
        static:
          header_1: first header
          header_2: second header
      body:
        static: "build.sbt"