name: Test name
port: 9999
endpoints:
- path: /test
  method: GET
  action:
    staticMockResponse:
      headers:
        'X-HEADER_1':
          - first: a
          - second: b
        'X-HEADER_2': second header
      headersPath: 'test-config-headers.yaml'
      bodyPath: "build.sbt"